name: Publish package to GitHub Packages
on:
  release:
    types: [ created ]
  push:
    branches: [ develop ]


jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build with Gradle
      run: gradle build

    - name: Publish to GitHub Packages
      run: ./.github/publish.sh
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

